### ISSUE TITLE
Add audio to generated spectrogram from original video.

### ISSUE THREAD

**Issue by CYCLOP5** [CYCLOP5/Video-To-Spectrogram#1]
Make sure the audio is of the specified duration of the generated spectrogram incase end user doesn't get error if all frames of the original video aren't generated.

Work on this on Audio-Fixes Branch.

**Comment by CYCLOP5** [comment]
Compatibility issues with avi and mp4 codecs

**Comment by AceofStades** [comment]
I'll start working on it on Sunday.

**Comment by CYCLOP5** [comment]
I did it all g
