### ISSUE TITLE
Transition to GUI

### ISSUE THREAD

**Issue by CYCLOP5** [CYCLOP5/Video-To-Spectrogram#4]
Use PYQT5 to make gui where the user can select a file and show progress bar in the GUI instead of terminal.

**Comment by CYCLOP5** [comment]
@rahulbok

**Comment by AceofStades** [comment]
Got it boss.

**Comment by CYCLOP5** [comment]
I'll fix the indentation error today and push

**Comment by CYCLOP5** [comment]
It's fixed feel free to pull and continue @rahulbok

**Comment by CYCLOP5** [comment]
Completed
